services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run utama2.py --server.port $PORT --server.enableCORS false
    plan: free